config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users 
  root to: 'welcome#index'
  get 'my_portfolio', to: "users#my_portfolio"  
  get 'search_stocks', to: "stocks#search"
  get 'my_friends', to: "users#my_friends"
  post 'add_friend', to: "users#add_friend"
   
   
  resources :user_stocks, only: [:create, :destroy]
  resources :users , only: [:show, :destroy]
  resources :notes , only: [:new,:create,:index]
  get 'search-friends' , to: 'users#search'
  
end

app/views/friends/_lookup.html.erb
<h3>Search for Friends</h3>

<div id="friend-lookup"> 
    <%= form_tag search_friends_path, remote: true,  method: :get, id: "friend-lookup-form" do %>
        <div class="row form-group no-padding text-center">
        
            <div class="col-md-10"> 
                <%= text_field_tag :search, params[:search],
                placeholder: "Enter first name, last name  or email", 
                autofocus: true, 
                class: 'form-control search-box input-lg'
                %>                
            </div>
            <div class="col-md-2">
                <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
                    <%= fa_icon "search" %>
                    Search
                <% end %>
            </div>
        </div>
    
    <%end%>
</div> 
<div id="results">
    <%= render 'friends/result' %>
</div>

app/views/friends/_result.html.erb
<% if params[:action] == 'search' %>
    <div class="result-block">
        <%= bootstrap_flash %>
    </div>
<%end%>
<% if  !@users.blank? %>
    <div id="friend-lookup-results" class="well results-block col-md-10">
        <table class="search-results-table col-md-12">
            <tbody>
                <% @users.each do |user| %>
                    <tr>
                        <td><strong>Name:</strong><%= user.full_name %></td>
                        <td><strong>Email:</strong><%= user.email %></td>
                        <td>
                            <strong>Profile:</strong><%= link_to "View Profile", user_path(user), class: 'btn btn-xs btn-success'%>
                            <% if current_user.not_friends_with?(user.id) %>
                                <%= link_to "Add as my friend",
                                               add_friend_path(user: current_user, friend: user),
                                               class: 'btn btn-xs btn-success',
                                               method: :post %>
                            <%else%>
                            <span class="label label-primary">You are already friends</span>
                            <%end%>
                        </td>
                    </tr>
                <%end%>
            </tbody>
        </table>
    </div> 
<% end %>

app/views/friends/_result.js.erb
$('#results').html("<%= j (render 'friends/result.html') %>")