config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users 
  root to: 'welcome#index'
  get 'my_portfolio', to: "users#my_portfolio"  
  get 'search_stocks', to: "stocks#search"
  get 'my_friends', to: "users#my_friends"
  post 'add_friend', to: "users#add_friend"
   
   
  resources :user_stocks, only: [:create, :destroy]
  resources :users , only: [:show, :destroy]
  resources :notes , only: [:new,:create,:index]
  get 'search-friends' , to: 'users#search'
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :user_stocks, :dependent => :destroy
         has_many :stocks, through: :user_stocks 
         has_many :friendships
         has_many :friends, through: :friendships 
         has_many :notes 
         def full_name             
             return "#{first_name} #{last_name}".strip if first_name || last_name
             "Anonymos"
         end
         
         def stock_already_added?(ticker_symbol)
           stocks_matching_ticker = Stock.where(ticker: ticker_symbol) 
           return false unless stocks_matching_ticker.present?
           stocks.exists?(id: stocks_matching_ticker.pluck(:id))
         end
         
         def under_stock_limit?
           (user_stocks.count < 10)
         end
         
         def can_add_stock? ticker_symbol
           under_stock_limit? && !stock_already_added?(ticker_symbol)
         end
         
         def self.search(params)                
                 params.strip!
                 params.downcase!
                 to_send_back = (first_name_matches(params)+
                                 last_name_matches(params)+  
                                 email_matches(params)).uniq
                 return nil unless to_send_back
                 to_send_back             
         end
         
         
         def self.first_name_matches params
             matches("first_name", params)
         end
         
         def self.last_name_matches params
             matches("last_name", params)
         end
         
     
         
         
         
         
         def self.email_matches params
             matches("email", params)
         end
         
         def self.matches(field_name, params)
             User.where("#{field_name} like ?", "%#{params}%")
         end
         
         def except_current_user(users)
             users.reject{ |user| user.id == self.id }
         end
         
         def not_friends_with?(friend_id)
            friendships.where(friend_id: friend_id).count < 1 
         end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @user_stocks = @user.stocks
  end
  
  def my_friends
    @friendships = current_user.friends 
  end
  
  def add_friend
    friend = User.find(params[:friend])
    
    # or
    
    # current_user.friendships.build friend_id: @friend.id
    # if current_user.save
      
      
    if Friendship.create!( user_id: params[:user], friend_id: params[:friend])
      flash[:success] = "#{friend.full_name} now is friend with you"
    else
      flash[:danger] = "There was something wrong with the friend request"
    end
    redirect_to my_friends_path 
  end
  
  def search
    if params[:search].blank?
      flash.now[:danger] = "You have entered an empty search string"
    else      
      @users = User.search(params[:search])    
      @users = current_user.except_current_user(@users)
      flash.now[:danger] = "No users match this search criteria" if  @users.blank?
    end
    respond_to do |format|
       format.js { render partial: "friends/result"}
    end
 
  end
  
  
  
  
  def show 
    @user = User.find(params[:id])
    @user_stocks = @user.stocks
  end
  
  def destroy
    # @friendship = current_user.friendships.wehre(friend_id: params[:id]).first
    # or
     @friendship = Friendship.where(friend_id: params[:id]).first  
     unfriended_full_name = User.find(params[:id]).full_name   
     if  @friendship.destroy
      flash[:notice] = "You unfriended #{unfriended_full_name}"
     else
       flash[:danger] = "Something went wrong during unfriending #unfriended_full_name}"
     end
      redirect_to my_friends_path
   
  end
  
end

app/helpers/user/registraitons_helper.rb
module User::RegistraitonsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_result.html.erb
<% if params[:action] == 'search' %>
    <div class="results-block">
        <%= bootstrap_flash %>
    </div>
<% end %>
<% if @stock %>
    <div class="well results-block">
      <strong>Symbol: </strong> <%= @stock.ticker %>
      <strong>Name: </strong> <%= @stock.name %>
      <strong>Price: </strong> <%= @stock.last_price %>
      <% if current_user.can_add_stock?(@stock.ticker) %>
          <%= link_to "Add to my stocks", user_stocks_path(user: current_user, stock_ticker: @stock.ticker),
                                      class: 'btn btn-xs btn-success', method: :post %>
      <% else %>
      <span class="label label-default">
          Stock cannot be added because you have already added
          <%if !current_user.under_stock_limit? %>
              10 stocks
          <% end %>
          <% if current_user.stock_already_added?(@stock.ticker)%>
              this stock
          <% end%>
      </span>      
      <%end%>
    </div>
<% end %>

app/views/users/_result.js.erb
$('#results').html("<%= j (render 'users/result.html') %>")

app/views/users/my_friends.html.erb
<%= render 'friends/lookup' %>

<% if @friendships.size > 0  %>
  <table class="table table-stripped">
    <thead>
        <tr>
            <th colspan="3" class="page-header">
                <h2>My Friends</h2>
            </th>
        </tr>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <% @friendships.each do |friend| %>
        <tr>
            <td> <%= friend.full_name%></td>
            <td> <%= friend.email%></td> 
            <td> <%= link_to "View Profile", user_path(friend), class: 'btn btn-primary btn-xs' %></td>
            <td>
            <%= link_to "unfriend" , user_path(friend),
                                       method: :delete,
                                       data: {confirm: "Are you sure you want to unfriend #{friend.full_name}?"},
                                       class: 'btn btn-danger'%>
              
            </td>
        </tr>      
        <% end %>
    
    </tbody>
</table>
<% else %> 
    <div class="row col-lg-12 col-md-12">
        <p class="lead">You don't have any friends yet. Please add some!</p>
    </div>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<h3>Search for Stocks</h3>
<div id="stock-lookup"> 
    <%= form_tag search_stocks_path, remote: true,  method: :get, id: "stock-lookup-form" do %>
        <div class="row form-group no-padding text-center">
        
            <div class="col-md-10">
            <!-- :stock is the name of text_field and params[:stock] is the value -->
                <%= text_field_tag :stock, params[:stock],
                placeholder: "Stock ticker symbol", 
                autofocus: true, 
                class: 'form-control search-box input-lg'
                %>                
            </div>
            <div class="col-md-2">
                <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
                    <%= fa_icon "search" %>
                    look up a stock
                <% end %>
            </div>
        </div>
    
    <%end%>
</div> 
<div id="results">
    <%= render 'users/result' %>
</div> 
<%= render 'stocks/list' %>

app/views/users/show.html.erb
<div class="well">  
    <h1><%= @user.full_name %> profile</h1>
    <h3>Email: <%= @user.email %></h3>
  </div>
</div>
<% if @user.stocks.size > 0 %>
<table class="table table-stripped">
    <thead>
        <tr>
            <th>Comapny Name</th>
            <th>Symbol</th>
            <th>Current Price</th>
            <th>Follow</th>
        </tr>
    </thead>
    <tbody>
        <% @user_stocks.each do |user_stock| %>
        <tr>
            <td> <%= user_stock.name%></td>
            <td> <%= user_stock.ticker%></td>
            <td> <%= user_stock.last_price%></td>
            <td> 
             <% if current_user.stock_already_added?(user_stock.ticker)%>
                <span class="label label-default">
                  Stock cannot be added because you have already added this stock
                </span>
             <%else%>
                <%= link_to "Add to my stocks", user_stocks_path(user: current_user, stock_ticker: user_stock.ticker),
                                          class: 'btn btn-xs btn-success', method: :post %>  
             <%end%>
            </td>
        </tr>      
        <% end %>
    
    </tbody>
</table>
<% else %>
    <p class="lead">This user is not tracking any stocks</p>
<% end %>