config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users 
  root to: 'welcome#index'
  get 'my_portfolio', to: "users#my_portfolio"  
  get 'search_stocks', to: "stocks#search"
  get 'my_friends', to: "users#my_friends"
  post 'add_friend', to: "users#add_friend"
   
   
  resources :user_stocks, only: [:create, :destroy]
  resources :users , only: [:show, :destroy]
  resources :notes , only: [:new,:create,:index]
  get 'search-friends' , to: 'users#search'
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
   
  end
  

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="container">
<h1>Welcome to the homepage of the finance tracker app</h1>
<h2><%#= DateTime.now.in_time_zone(current_user.time_zone) %></h2>
<hr /> 
<% date_range = (start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week).to_a %>
<div class="row">
    <div class="col-md-12 text-center">
        <div class="calendar-heading">
          <%= link_to '<', request.params.merge(start_month: t('date.month_names')[start_date.month-1] ) , class: 'btn btn-primary'%>     
          <span class="calendar-title" style="font-size: 20px"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>    
          <%= link_to '>', request.params.merge(start_month: t('date.month_names')[start_date.month+1]), class: 'btn btn-primary' %>
        </div>
    </div>
    <div class="col-md-12 col-xs-12 table-responsive toggle-circle-filled" style="margin: 0; padding: 0;">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <% date_range.slice(0,7).each do |day| %>
                        <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
                    <% end %>
                </tr>
            </thead>        
            <tbody>
            <% date_range.each_slice(7) do |week| %>
                <tr class="index-page">
                    <% week.each do |day| %>
                           <%= content_tag(:td,"", style: color_day(day))  do %>
                                <%= link_to day.mday, new_note_path(date: day), class: 'btn btn-xs btn-success' %>
                                <ul>
                                    <% stock_by_date(day).each do |s_d|%>
                                       <li> <%= s_d.stock.ticker%> </li>
                                    <% end %>                                   
                                </ul>
                                <%= link_to "notes", notes_path(date: day,id: current_user.id), method: :get , class: 'btn btn-info'  unless find_notes(day).empty? %>
                            </td>
                        <% end %>
                    <% end %>
                </tr>
            <% end %>
            </tbody>
        </table>
    </div>
</div> 
</div>